### ISSUE TITLE
pypika version compatibility

### ISSUE THREAD

**Issue by ghukill** [eduardogspereira/pypika-gis#1]
With PyPika now at version `0.30.0` on Pypi ([link](https://pypi.org/project/PyPika/)), wondering if this version requirement of `0.26.0` is needed or could be bumped in the `poetry.lock` file?

https://github.com/eduardogspereira/pypika-gis/blob/master/poetry.lock#L100

I'm using syntax that only works with pypika `0.30.0`, and as such, without some hackery, cannot pip install these complimentary libraries (deploying via Docker, adding complexity to more manual installs of these libs).  

Asking, because this looks just precisely what I could use, and would love to not have to recreate the functionality!  Thanks.

**Comment by eduardogspereira** [comment]
Hi @ghukill.

Sorry for the delay, I only saw the message now. 
I updated the project setup (version 1.2.3), it should work with any pypika 0.* version now. 

Let me know if it works fine for you :cowboy_hat_face:

**Comment by ghukill** [comment]
Apologies are mine now, just returning to this!  Thanks for making the change.  Anticipating it will work, will update here if any problems.  Thanks again!
